### ISSUE TITLE
Convert PropertyTranslation plugin to a store based feature

### ISSUE THREAD

**Issue by wazolab** [teritorio/vido#169]
As of today we have `plugins/property-translations.ts` acting as a global helper injected in Nuxt instance.
We want to rebase this plugin within `siteStore`

**TODO**
- [x] Move property-translations.ts functions `p()` and `pv()` to siteStore getters
- [x] Remove `globalTranslations` usage
- [x] Remove $propertyTranslations global helper
- [x] Remove the plugin import across the project
